export default {
  url: 'https://tigger.dev',
  title: 'fronttigger',
  subtitle: 'fronttigger',
  description: "fronttigger's blog",
  thumbnail: '',
  author: {
    name: 'fronttigger',
    thumbnail: '/tigger.jpeg',
    bio: 'frontend engineer',
    contacts: {
      email: 'fronttigger@gmail.com',
      facebook: '',
      telegram: '',
      twitter: '',
      github: 'https://github.com/fronttigger',
      rss: '',
      linkedin: 'https://www.linkedin.com/in/%EC%A4%80%ED%98%95-%EA%B9%80-822722214',
      instagram: '',
      line: '',
      gitlab: '',
      codepen: '',
      youtube: '',
      soundcloud: '',
    },
  },
}
